name: Deployment Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
    types: [opened, synchronize]

env:
  DEPLOYMENT_CONDITION: ${{ github.event_name == 'push' && !contains(toJSON(github.event.commits.*.message), '#skip') }}
  # TEST_MONGO_URL: ${{ secrets.TEST_MONGO_URL }}
  JWT_SCR_KEY: ${{secrets.JWT_SECRET}}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: echo "works"

  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      TEST_MONGO_URL: mongodb://127.0.0.1:27017/fullstack_test
    outputs:
      tag_release_can_run: ${{steps.final.outcome == 'success'}}
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with: 
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: lint
        run: npm run lint
      - name: test client
        run: npm run client-test
      - name: test server
        run: npm run server-test
      - name: Deploy to render
        id: final
        uses: JorgeLNJunior/render-deploy@v1.4.7
        if: ${{env.DEPLOYMENT_CONDITION == 'true' }}
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          wait_deploy: true 
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: ${{needs.simple_deployment_pipeline.outputs.tag_release_can_run == 'true'}}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
  # notify_discord:
  #   needs: [simple_deployment_pipeline]
  #   runs-on: ubuntu-latest
  #   if: ${{always()}}
  #   steps:
  #     - name: title
  #       run: echo ${{env.DEPLOYMENT_CONDITION}}
  #     - name: Discord Success Notification
  #       uses: hunghg255/action-notifications@master
  #       if: ${{needs.simple_deployment_pipeline.result == 'success' && env.DEPLOYMENT_CONDITION == 'true'}}
  #       with:
  #         discord_webhook: ${{ secrets.DISCORD_WEBHOOK }}
  #         title: New build deployed
  #         description: Test at https://full-stack-bloglist.onrender.com
  #     - name: Discord Failure Notification
  #       uses: hunghg255/action-notifications@master
  #       if: ${{ needs.simple_deployment_pipeline.result != 'success' && env.DEPLOYMENT_CONDITION == 'true'}}
  #       with:
  #         discord_webhook: ${{ secrets.DISCORD_WEBHOOK }}
  #         title: New build deployement
  #         status: failure
